### ISSUE TITLE
Relative image links

### ISSUE THREAD

**Issue by nodiscc** [justinwalsh/daux.io#162] opened 2014-04-23 00:51 UTC
Hi, thanks for you work on this nice tool. I sometimes need to embed images in my documentation, so I use `![](https://avatars1.githubusercontent.com/u/3950390?s=140)` in my markdown file and it renders like
![](https://avatars1.githubusercontent.com/u/3950390?s=140)

In Github READMEs it is also possible to use a relative URL for images (eg `![](images/schema.png)` or `![](screenshot.png)`, whereas daux.io displays nothing when I use a relative path.

How is it possible to display images living in the same directory as the docs?

**Comment by razbakov** [comment] 2015-03-25 15:49
Agree. I also just moved to mdwiki. daux was promising

**Comment by agileadam** [comment] 2015-03-26 21:33
I have achieved relative pathing for images by tweaking the generate_page() function slightly.

This isn't as clean as it could be, but I've added this just above the last return statement in `libs/daux_page.php`

```php
// Convert relative paths to absolute paths
// Example: In {docs}/Foo_Topic rewrite src="images/foo.png" to src="//mysite.com/daux/docs/Foo_Topic/images/foo.png"
// Example: In {docs}/Bar_Topic rewrite src="../img/foo.png" to src="//mysite.com/daux/docs/Bar_Topic/../img/bar.png"
//   Believe it or not, that URL will work
$path_parts = explode('/', $this->path);
array_pop($path_parts);
$dir_path = $params['base_url'] . implode('/', $path_parts) . '/';
$page['content'] = str_replace('src="', 'src="' . $dir_path, $page['content']);
```

Basically I just look for image tags and change them from relative to absolute. So you can use `test.png` or `images/test.png` or `../images/test.png` and they'll all work correctly (at least in my testing they do).

**Comment by mc007** [comment] 2015-05-01 00:33
same here, any other md files containing md image tags are plain incompatible, thats indeed deal breaker. 
I know what's the reason for the 404s: you are removing the 'docs' part from the urls.

**Comment by onigoetz** [comment] 2015-07-21 12:07
This is now fixed and works in the develop branch, it will be merged very soon

**Closed by onigoetz** 2015-07-21 12:07 UTC

**Comment by JayHoltslander** [comment] 2015-07-21 20:38
@onigoetz Good to hear. I just finished setting up my first Daux site and started adding content and discovered this issue. Indeed a deal breaker. Looking forward to the fix.

**Comment by onigoetz** [comment] 2015-07-21 20:46
You can already grab it from the develop branch if you want to test it early, the only reason we don't merge to master right now are technical on our side.

**Comment by JayHoltslander** [comment] 2015-08-05 21:37
@onigoetz So I backed up and wiped out my copy of Daux. Downloaded the dev branch. Tried to run it but get:

<blockquote>Parse error: syntax error, unexpected '[', expecting ')' in phar:///nfs/c10/h01/mnt/150243/domains/support.myserver.ca/html/daux/daux.phar/vendor/react/promise/src/functions.php on line 68</blockquote>

How can I resolve this?

**Comment by onigoetz** [comment] 2015-08-06 06:28
This means you are on php 5.3, you must at least be on php 5.4

**Comment by JayHoltslander** [comment] 2015-08-06 18:01
Aha. Thanks. Working now.

**Comment by vheun** [comment] 2016-01-07 22:23
Hello everyone. It seemed like this should be solved, but it does not work.
When I have ![](image.png) in a file within a subfolder and the image is placed in the same sub folder, the image is not being presented. The image link ignores the subfolder. I tried the master and the developer branch.

Is there anything I should configure?

**Comment by onigoetz** [comment] 2016-01-07 22:39
Hi,I'm not sure to understand what you mean.
How do you link to your image exactly ?
Envoyé via Outlook Mobile

**Comment by vheun** [comment] 2016-01-07 22:55
Lets say I have a structure like that:

```
│ index.md
│
└─── folderX
     │index2.md
     │image.png
```
If I link the image within index2.md like so `![](image.png)` it will not be shown.
On the generated page the link for image.png will be **"webpage/image.png"** it should be **"webpage/folderX/image.png"**

**Comment by onigoetz** [comment] 2016-01-08 08:40
That's weird, I do it exactly like that in my documentations and it works. 

What is the exact name of the folder and file ? are there special characters inside ?

**Comment by vheun** [comment] 2016-01-08 16:33
The bug is reproduced with the exact example as the structure above.

I experimented a bit more. 
The error occurs when I set `"inherit_index": true`.
If I then click on the folderX menu item, it opens the content from index2.md but image.png is pointed to *"webpage/image.png"*

When I click on the index2 menu item, the image link is pointed to the right position.
