### ISSUE TITLE
Missing Search...

### ISSUE THREAD

**Issue by enesyteam** [justinwalsh/daux.io#353] opened 2016-03-01 11:51 UTC
Please write a search module for this!

**Comment by dkisselev** [comment] 2016-03-01 16:44
This is a duplicate of #18, and implementations have been proposed but are awaiting review in #257 & #351. Please search the issues to see if a request has already been made, and leave a simple +1 if you want to express that you're also looking for a feature (or even help test pull requests to make it easier for us to review/merge).

Daux is an open-source project, so anyone can contribute and review to help get features in. We all have day jobs, so cannot resolve every issue ticket right away (especially if it has to do with a feature that doesn't personally bother us; any time we would put into daux is more likely to go into what we use).

**Closed by dkisselev** 2016-03-01 16:44 UTC
