### ISSUE TITLE
Is there a config option to keep all menus unfolded instead of hiding the submenus?

### ISSUE THREAD

**Issue by vheun** [justinwalsh/daux.io#346] opened 2016-02-07 23:10 UTC
I would like to just easily keep all menus open. It gives a user a better overview of all subjects.

**Comment by onigoetz** [comment] 2016-02-28 22:28
Hello,
this is not possible today, but it is planned to support it one day.

I will close this issue as this is a duplicate of #277 . You can subscribe to that issue to keep track of your request

**Closed by onigoetz** 2016-02-28 22:28 UTC
Labels: Duplicate, Feature Request
