### ISSUE TITLE
Styles for code blocks are broken on wide screens

### ISSUE THREAD

**Issue by sergii-tkachenko** [justinwalsh/daux.io#269] opened 2015-04-21 14:57 UTC
When a window is wider than 1149px `code` blocks are positioned to the right of the `#content-page`:
![image](https://cloud.githubusercontent.com/assets/672669/7255087/c8d1d116-e84f-11e4-9568-6c3b8c7cfdb8.png)

**Comment by dkisselev** [comment] 2015-04-21 17:07
Duplicate of #25, it's a configurable feature. (https://github.com/justinwalsh/daux.io#code-floating)

**Closed by dkisselev** 2015-04-21 17:07 UTC

**Comment by sergii-tkachenko** [comment] 2015-04-21 17:08
Thank you, and sorry, I was looking for this issue only among the opened ones.

**Comment by dkisselev** [comment] 2015-04-21 17:10
No worries, it's come up a lot but the issues are all old and closed so it's hard to find.
