### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by gbaumgart** [justinwalsh/daux.io#374] opened 2016-06-02 12:48 UTC
Consider a file located at: 

./Widgets/index.md with the [content](https://github.com/ibm-js/deliteful/blob/master/docs/index.md) : 

```
## Basic Widgets

* [Button](Button.md)
```

whereby the file Widgets/Button.md really exists. 

However, this works when browsing md files on Github but when browsing this with daux.io (pretty urls =on), you will get an 404 error when clicking the Button link. So this is representing already the first bug. Currently you would have to modify the index.md file for 

```
## Basic Widgets

* [Button](Widgets/Button)
```

to make this work for daux.io but it will break that links when reading this on Github/Gitlab and others.

The follow-up bug comes in when using the static version.

if you would use the Github compatible version:

```
* [Button](Button.md)
```

you will be redirected to Widgets/Button.md which is a 404 of course 

With the non Github compatible version:

```
* [Button](Widgets/Button)
```

you land at Widgets/Button which is also a 404

Now, I am not sure this is a bug in the Markdown parser or the static generator or both. I am also not sure that daux.io has no intentention to be compatible to Github Markdown at all. 

Any thoughts on this? 

thanks,
g

**Comment by gbaumgart** [comment] 2016-06-02 12:52
I placed a static version of my docs [here](https://cdn.rawgit.com/net-commander/windows-dist/master/docs/Interface_Designer/Widgets/index.html). 

You will see that navigation part on the left works, but not that links coming from the content.

**Comment by onigoetz** [comment] 2016-06-08 09:50
Hmmm,

I think the problem is even deeper than that.

__Works on Github__
```
* [Button](Button.md)
```

__Works on Daux.io Live__
```
* [Button](Widgets/Button)
```

__Works on Daux.io Static__
```
* [Button](Widgets/Button.html)
```

__Works on Daux.io Live and Static__
```
* [Button](!Widgets/Button)
```

The only way to make it work on all three is to be able to find relative links `(Button.md)` and transform them when used in Daux.io.

I will experiment with this when I'm back from vacations

**Comment by gbaumgart** [comment] 2016-06-08 09:56
Hi Stephane, thanks for looking at this. I think this might be the cause for broken images as well (still can't use relative paths, using master). However, I gonna dive now into the daux "processors" in order to figure out how i can replace the navigation part with my own "grids" (like in file managers).

about "net-commander", its basically a tool for automating devices/services, not really meant for the public (yet).

enjoy your holiday.

**Comment by onigoetz** [comment] 2016-07-01 21:36
Hi,

Just a quick update to say I didn't abandon you. :-)

I have an almost working version which can resolve all files both in relative and absolute, I will try to commit it before the end of the weekend.

**Comment by gbaumgart** [comment] 2016-07-01 22:01
hey Stephan, thanks a lot,
you're my Github hero of the month!

**Comment by onigoetz** [comment] 2016-07-04 18:36
Hello,

I published my changes in the development branch : http://dev.daux.io/Features/Internal_links

I will fix some other issues related to relative links before I push everything to the main branch

**Comment by onigoetz** [comment] 2016-07-29 20:48
It's live :D

**Comment by gbaumgart** [comment] 2016-07-31 09:45
hi, thanks a lot, so i tried my docs against master but its crashing in quite some places. 

if you like, here the docs : https://github.com/net-commander/net-commander-documentation.git

If you open "Interface Designer" -> Widgets or any of the sub pages, its crashing because of missing files, it also does crash on external links, see "Components".

Its of course possible that my links are not adjusted to the new daux but i wanted to let you know just.

thanks,
g

**Comment by onigoetz** [comment] 2016-08-02 20:44
Hi,

If I look at the source of the page, you describe the links that way : 

    ...
    ## Basic Widgets

    * [Button](Widgets/Button)
    * [Checkbox](Widgets/Checkbox)
    * [Combobox](Widgets/Combobox)
    ...

But it should be:

    ...
    ## Basic Widgets

    * [Button](Button)
    * [Checkbox](Checkbox)
    * [Combobox](Combobox)
    ...

Because you're already in the Widgets directory.

Apart from that it seems there is a problem in the URL generation, I will investigate to fix that.

**Comment by onigoetz** [comment] 2016-08-02 21:42
Hi, I pushed a fix to the development branch that resolves the URL generation problem, can you give it a try ?

**Comment by gbaumgart** [comment] 2016-08-03 13:09
hey, i am back next monday.

**Comment by gbaumgart** [comment] 2016-08-09 18:07
hi, so i updated to latest and tried again with the changes needed in the doc files = works but it crashes too often on with  'Could not locate file' . It's true that sometimes that files don't exists but I'd really prefer it's just not crashing in that cases, just as on Github. Apart from that minor issue, it's seems way better than before. I am also happy with your default theme changes, its readable now out of the box :-)

that's the folder of interest : https://github.com/ibm-js/deliteful/tree/master/docs. but as said, making it not crashing is all what's left to do :-)

thanks a lot.

**Comment by onigoetz** [comment] 2016-08-10 06:52
Okay great, thanks for your feedback.
I'll change the code to make links red when they're broken, I created issue #395 for that.

**Closed by onigoetz** 2016-08-10 06:52 UTC
Labels: Feature Request, Fixed in Development

**Comment by gbaumgart** [comment] 2016-08-10 08:25
@onigoetz Great, I hope you're adding just a CSS class for that, something which can be styled via themes. 

thanks a lot.
